import Link from "next/link";
import { COMPANY, CONTACT_EMAIL, LegalPage, Section } from "../legal";
import { APP_HOST } from "@/lib/site";

export const metadata = { title: "Privacy policy", description: "What Perk collects from shops and customers, how it is used, and your rights under the NZ Privacy Act 2020." };

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" intro="Perk is a digital loyalty (stamp) card service for shops, delivered via Apple Wallet, Google Wallet, or a web card. This policy explains what we collect, how we use it, and the rights you have.">
      <Section title="1. Information we collect">
        <p>What we collect depends on whether you&rsquo;re a <strong>Shop owner or staff member</strong> or a <strong>customer</strong>.</p>
        <p><strong>Shop owners and staff:</strong></p>
        <ul>
          <li>Your email address, used to sign you in via a magic link (we don&rsquo;t store passwords).</li>
          <li>Shop details you enter: shop name, brand colour/logo, stamp threshold, reward description, and your shop&rsquo;s custom URL (e.g. <code>{APP_HOST}/your-shop</code>).</li>
          <li>A staff PIN: a six-digit code generated by Perk (not chosen or provided by you) to authenticate scanner access on any device, without individual staff accounts. You can refresh it at any time, which signs out all devices currently using it.</li>
        </ul>
        <p><strong>Customers:</strong></p>
        <p>Perk is anonymous by default. Customers don&rsquo;t sign up or create an account to receive or use a card. We collect:</p>
        <ul>
          <li>A unique card identifier (e.g. <code>ABCD-2345</code>), generated automatically when a card is issued.</li>
          <li>Stamp, redemption, and adjustment events recorded against that card, each with a timestamp and a source (staff, self-serve, or shop owner).</li>
          <li>An email address, only if a customer chooses to back up their card. It is used solely to re-send the card link.</li>
          <li>Basic technical data incidental to issuing and updating wallet passes or the web card (e.g. IP address at the time of a scan, device type), used for fraud prevention such as self-serve stamping cooldowns.</li>
        </ul>
        <p>If a customer adds a pass to Apple Wallet or Google Wallet, the pass content (stamp count, shop branding) is also held on the customer&rsquo;s device and passed through Apple&rsquo;s or Google&rsquo;s wallet infrastructure, governed by Apple&rsquo;s and Google&rsquo;s own privacy practices.</p>
      </Section>

      <Section title="2. How we use your information">
        <ul>
          <li>To operate Shop dashboards, custom URLs, and staff scanner access.</li>
          <li>To issue, update, and back up digital stamp cards and wallet passes.</li>
          <li>To maintain the stamp/reward ledger, including letting Shop owners correct a missed or mistaken stamp.</li>
          <li>To prevent abuse, for example cooldowns that stop repeat self-serve stamping.</li>
          <li>To respond to support enquiries from Shop owners or customers.</li>
          <li>To maintain and improve the security and reliability of Perk.</li>
        </ul>
        <p>We do not sell your personal data to third parties, and we do not use customer stamp-card data for advertising.</p>
      </Section>

      <Section title="3. Data storage">
        <p>Perk&rsquo;s data is stored with our cloud hosting and database providers. Where a Shop&rsquo;s dashboard shows customer card activity, that data is limited to cards issued by that Shop. Shops cannot see other Shops&rsquo; data.</p>
      </Section>

      <Section title="4. Third-party services">
        <p>We use the following third-party services, each with their own privacy practices:</p>
        <ul>
          <li><strong>Apple and Google</strong>: to issue and update Wallet passes (stamp count, branding, and pass identifier are transmitted to their wallet infrastructure).</li>
          <li><strong>A cloud hosting and database provider</strong>: to run Perk and store Shop and card data.</li>
          <li><strong>A transactional email provider</strong>: to send magic-link sign-in emails and, where a customer opts in, card backup emails.</li>
        </ul>
      </Section>

      <Section title="5. Your rights">
        <p>Under the New Zealand Privacy Act 2020, you have the right to:</p>
        <ul>
          <li><strong>Access</strong> the personal information we hold about you.</li>
          <li><strong>Correct</strong> any personal information that is inaccurate or misleading.</li>
          <li><strong>Delete</strong> your account (or, for customers, your card record and any backup email). We will process such requests within 30 days.</li>
        </ul>
        <p>Because Perk cards are anonymous by default, most customers hold no personal information with us beyond the card ledger tied to an anonymous card identifier. If you&rsquo;ve added a backup email, you can ask us or your Shop to remove it, or request deletion of your card record.</p>
        <p>We retain Shop account and card data for as long as the account or card is active. If you request deletion, your data will be removed within 30 days, except where we must retain minimal records for fraud prevention, dispute resolution, or legal compliance.</p>
        <p>If a privacy breach occurs that poses a serious risk of harm, we will notify the New Zealand Privacy Commissioner and affected individuals as required by law.</p>
        <p>To exercise any of these rights, contact us via the email below.</p>
      </Section>

      <Section title="6. Children's privacy">
        <p>Perk is not directed at children. We do not knowingly collect personal data from children. If you believe a child has provided us with their data, please contact us and we will delete it promptly.</p>
      </Section>

      <Section title="7. Changes to this policy">
        <p>We may update this policy from time to time. We will notify you of material changes by email or by prominent notice on the platform before they take effect. Continued use after that notice constitutes acceptance of the revised policy.</p>
      </Section>

      <Section title="8. Contact">
        <p>Questions? Reach us at <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p>
        <p>Perk is a product of {COMPANY}. See also our <Link className="underline" href="/terms">Terms &amp; Conditions</Link>.</p>
      </Section>
    </LegalPage>
  );
}
