import Link from "next/link";
import { COMPANY, CONTACT_EMAIL, LegalPage, Section } from "../legal";

export const metadata = { title: "Terms & Conditions", description: "The terms for shops and customers using Perk." };

export default function TermsPage() {
  return (
    <LegalPage title="Terms & Conditions" intro="These terms cover the use of Perk by shops that run a loyalty programme and by customers who hold a card. By accessing or using Perk you agree to them.">
      <Section title="1. Acceptance of terms">
        <p>By accessing or using Perk (&ldquo;the platform&rdquo;), you agree to be bound by these Terms &amp; Conditions. If you do not agree, please do not use the platform.</p>
      </Section>

      <Section title="2. Description of service">
        <p>Perk lets shops (&ldquo;Shops&rdquo;) create branded digital stamp cards for their customers, generate a shop URL and printable poster, and record stamps and reward redemptions. Customers can add a card to Apple Wallet or Google Wallet, or use a web card, without creating an account. As the platform is in active development, features may change or be discontinued.</p>
      </Section>

      <Section title="3. Eligibility">
        <p>You must be authorised to act on behalf of the business you register as a Shop, and at least 18 years old to create a Shop account. Customers using a card have no age requirement beyond what applies at the issuing Shop.</p>
      </Section>

      <Section title="4. User accounts">
        <p>Shop sign-in uses a magic link sent to your email address; you&rsquo;re responsible for keeping access to that email address secure. Staff scanner access is controlled by a six-digit PIN, auto-generated by Perk, which you can refresh at any time (for example, to sign out of all devices at once). You are responsible for all activity conducted under your Shop&rsquo;s account or PIN, whether or not authorised by you.</p>
      </Section>

      <Section title="5. Shop content and customer cards">
        <p>By entering your Shop&rsquo;s name, branding, logo, or reward rules, you grant Perk a non-exclusive, royalty-free licence to use that content solely to operate your Shop&rsquo;s card, poster, and web page. You warrant that your Shop content is accurate and does not violate any third-party rights.</p>
        <p>Customer card data (stamp counts, rewards, and redemption history) is maintained in a ledger tied to each card and is visible to the Shop that issued it. Shop owners may manually adjust a card&rsquo;s stamp count (for example, to correct a missed stamp); such adjustments are recorded in the ledger with an attributable source. Rewards, stamp thresholds, and redemption rules are set and controlled by each Shop, not by Perk &mdash; disputes about reward eligibility are between the customer and the Shop.</p>
        <p>We reserve the right to remove any content that we determine, in our sole discretion, to be inaccurate, offensive, or otherwise inappropriate.</p>
      </Section>

      <Section title="6. Acceptable use">
        <p>You agree not to:</p>
        <ul>
          <li>Use Perk for any unlawful purpose, or in a way that infringes the rights of others;</li>
          <li>Attempt to circumvent stamping limits, cooldowns, or PIN protections to defraud your own or another Shop;</li>
          <li>Reverse engineer, scrape, or interfere with the operation or security of Perk;</li>
          <li>Use Perk to collect personal information from customers beyond what the service itself facilitates (i.e. the optional card backup email);</li>
          <li>Upload branding, logos, or content you do not have the right to use.</li>
        </ul>
        <p>We may suspend or terminate access to Perk for Shops that breach these terms.</p>
      </Section>

      <Section title="7. Pricing">
        <p>Perk is currently provided free of charge, with no payment card details required. We may introduce paid plans or usage limits in future; if we do, we will give existing Shops reasonable advance notice by email or prominent notice on the platform before any change takes effect for them.</p>
      </Section>

      <Section title="8. Third-party services">
        <p>Perk relies on third-party services, including Apple Wallet, Google Wallet, and our hosting and database providers, to operate. Use of Apple Wallet or Google Wallet passes is also subject to Apple&rsquo;s and Google&rsquo;s own terms and policies, which we do not control. We are not responsible for outages, changes, or issues caused by these third-party services.</p>
      </Section>

      <Section title="9. Intellectual property">
        <p>All content, design, and code on the platform (excluding Shop-submitted content and content provided by or licensed from third parties) is the property of {COMPANY} and may not be reproduced without permission. You retain ownership of your Shop&rsquo;s branding, logo, and content that you upload, subject to the licence in section 5.</p>
      </Section>

      <Section title="10. Limitation of liability">
        <p>The platform is provided &ldquo;as is&rdquo; without warranties of any kind, including as to availability, accuracy, or fitness for a particular purpose. To the fullest extent permitted by law, {COMPANY} shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform &mdash; including loss of stamp or reward data. Nothing in these terms limits any liability that cannot be excluded under applicable New Zealand law, including the Consumer Guarantees Act 1993 and the Fair Trading Act 1986.</p>
      </Section>

      <Section title="11. Governing law">
        <p>These terms are governed by the laws of New Zealand. Any disputes shall be subject to the exclusive jurisdiction of the New Zealand courts.</p>
      </Section>

      <Section title="12. Privacy">
        <p>Your use of the platform is also governed by our <Link className="underline" href="/privacy">Privacy Policy</Link>, which is incorporated into these terms by reference.</p>
      </Section>

      <Section title="13. Changes to these terms">
        <p>We may revise these terms at any time. We will notify you of material changes by email or by prominent notice on the platform before they take effect. Continued use after that notice constitutes acceptance of the updated terms.</p>
      </Section>

      <Section title="14. Termination">
        <p>Perk reserves the right to suspend or terminate your access to the platform at any time, including for breach of these terms or misuse of the platform. Upon termination, your right to use the platform ceases immediately. We will handle any retained personal data in accordance with our <Link className="underline" href="/privacy">Privacy Policy</Link>.</p>
      </Section>

      <Section title="15. Contact">
        <p>Questions about these terms? Contact us at <a className="underline" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p>
        <p>Perk is a product of {COMPANY}.</p>
      </Section>
    </LegalPage>
  );
}
